-- 00_setup.sql

CREATE OR REPLACE WAREHOUSE AIRFLOW_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE AIRLINE_DWH;

CREATE OR REPLACE SCHEMA AIRLINE_DWH.STAGE1_RAW;
CREATE OR REPLACE SCHEMA AIRLINE_DWH.STAGE2_DW;
CREATE OR REPLACE SCHEMA AIRLINE_DWH.STAGE3_MART;
CREATE OR REPLACE SCHEMA AIRLINE_DWH.AUDIT;
CREATE OR REPLACE SCHEMA AIRLINE_DWH.SECURITY;

CREATE OR REPLACE FILE FORMAT AIRLINE_DWH.STAGE1_RAW.CSV_FF
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null')
  DATE_FORMAT = 'MM/DD/YYYY';

CREATE OR REPLACE STAGE AIRLINE_DWH.STAGE1_RAW.AIRLINE_INT_STAGE
  FILE_FORMAT = AIRLINE_DWH.STAGE1_RAW.CSV_FF;

CREATE OR REPLACE TABLE AIRLINE_DWH.AUDIT.AUDIT_LOG (
  AUDIT_LOG_ID NUMBER AUTOINCREMENT,
  EVENT_TS     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  RUN_ID       STRING,
  PROC_NAME    STRING,
  TARGET_OBJECT STRING,
  ACTION       STRING,
  ROWS_AFFECTED NUMBER,
  QUERY_ID     STRING
);
