-- 01_tables.sql

CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE1_RAW.AIRLINE_RAW (
  SRC_ROW_ID          NUMBER,
  PASSENGER_ID        STRING,
  FIRST_NAME          STRING,
  LAST_NAME           STRING,
  GENDER              STRING,
  AGE                 NUMBER,
  NATIONALITY         STRING,
  AIRPORT_NAME        STRING,
  AIRPORT_COUNTRY_CODE STRING,
  COUNTRY_NAME        STRING,
  AIRPORT_CONTINENT   STRING,
  CONTINENTS          STRING,
  DEPARTURE_DATE      DATE,
  ARRIVAL_AIRPORT     STRING,
  PILOT_NAME          STRING,
  FLIGHT_STATUS       STRING,
  TICKET_TYPE         STRING,
  PASSENGER_STATUS    STRING,
  SRC_FILE_NAME       STRING,
  LOAD_TS             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE STREAM AIRLINE_DWH.STAGE1_RAW.AIRLINE_RAW_STREAM
  ON TABLE AIRLINE_DWH.STAGE1_RAW.AIRLINE_RAW
  APPEND_ONLY = TRUE;

CREATE OR REPLACE SEQUENCE AIRLINE_DWH.STAGE2_DW.SEQ_PASSENGER START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE AIRLINE_DWH.STAGE2_DW.SEQ_AIRPORT    START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE AIRLINE_DWH.STAGE2_DW.SEQ_PILOT      START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE AIRLINE_DWH.STAGE2_DW.SEQ_TICKET     START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE AIRLINE_DWH.STAGE2_DW.SEQ_STATUS     START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE AIRLINE_DWH.STAGE2_DW.SEQ_TRIP       START = 1 INCREMENT = 1;

CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE2_DW.DIM_PASSENGER (
  PASSENGER_SK NUMBER DEFAULT AIRLINE_DWH.STAGE2_DW.SEQ_PASSENGER.NEXTVAL,
  PASSENGER_ID STRING,
  FIRST_NAME   STRING,
  LAST_NAME    STRING,
  GENDER       STRING,
  AGE          NUMBER,
  NATIONALITY  STRING,
  PASSENGER_STATUS STRING,
  UPDATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DIM_PASSENGER PRIMARY KEY (PASSENGER_SK)
);

CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE2_DW.DIM_AIRPORT (
  AIRPORT_SK NUMBER DEFAULT AIRLINE_DWH.STAGE2_DW.SEQ_AIRPORT.NEXTVAL,
  AIRPORT_NAME STRING,
  AIRPORT_COUNTRY_CODE STRING,
  COUNTRY_NAME STRING,
  AIRPORT_CONTINENT STRING,
  CONTINENTS STRING,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DIM_AIRPORT PRIMARY KEY (AIRPORT_SK)
);

CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE2_DW.DIM_PILOT (
  PILOT_SK NUMBER DEFAULT AIRLINE_DWH.STAGE2_DW.SEQ_PILOT.NEXTVAL,
  PILOT_NAME STRING,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DIM_PILOT PRIMARY KEY (PILOT_SK)
);

CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE2_DW.DIM_TICKET_TYPE (
  TICKET_TYPE_SK NUMBER DEFAULT AIRLINE_DWH.STAGE2_DW.SEQ_TICKET.NEXTVAL,
  TICKET_TYPE STRING,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DIM_TICKET PRIMARY KEY (TICKET_TYPE_SK)
);

CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE2_DW.DIM_STATUS (
  STATUS_SK NUMBER DEFAULT AIRLINE_DWH.STAGE2_DW.SEQ_STATUS.NEXTVAL,
  FLIGHT_STATUS STRING,
  PASSENGER_STATUS STRING,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DIM_STATUS PRIMARY KEY (STATUS_SK)
);

CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE2_DW.FACT_TRIP (
  TRIP_SK NUMBER DEFAULT AIRLINE_DWH.STAGE2_DW.SEQ_TRIP.NEXTVAL,
  PASSENGER_SK NUMBER,
  AIRPORT_SK NUMBER,
  ARRIVAL_AIRPORT STRING,
  PILOT_SK NUMBER,
  TICKET_TYPE_SK NUMBER,
  STATUS_SK NUMBER,
  DEPARTURE_DATE DATE,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_FACT_TRIP PRIMARY KEY (TRIP_SK)
);

CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE3_MART.FACT_TRIP_ENRICHED (
  TRIP_SK NUMBER,
  PASSENGER_ID STRING,
  PASSENGER_NAME STRING,
  GENDER STRING,
  AGE NUMBER,
  NATIONALITY STRING,
  AIRPORT_NAME STRING,
  AIRPORT_COUNTRY_CODE STRING,
  COUNTRY_NAME STRING,
  AIRPORT_CONTINENT STRING,
  CONTINENTS STRING,
  ARRIVAL_AIRPORT STRING,
  PILOT_NAME STRING,
  FLIGHT_STATUS STRING,
  TICKET_TYPE STRING,
  PASSENGER_STATUS STRING,
  DEPARTURE_DATE DATE,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE3_MART.DAILY_KPI (
  KPI_DATE DATE,
  CONTINENTS STRING,
  FLIGHTS_CNT NUMBER,
  UNIQUE_PASSENGERS NUMBER,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
