-- 02_procedures.sql

CREATE OR REPLACE PROCEDURE AIRLINE_DWH.AUDIT.SP_LOG_AUDIT(
  RUN_ID STRING,
  PROC_NAME STRING,
  TARGET_OBJECT STRING,
  ACTION STRING,
  ROWS_AFFECTED NUMBER,
  QUERY_ID STRING
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO AIRLINE_DWH.AUDIT.AUDIT_LOG(
    RUN_ID, PROC_NAME, TARGET_OBJECT, ACTION, ROWS_AFFECTED, QUERY_ID
  )
  VALUES (
    :RUN_ID, :PROC_NAME, :TARGET_OBJECT, :ACTION, :ROWS_AFFECTED, :QUERY_ID
  );

  RETURN 'OK';
END;
$$;


CREATE OR REPLACE PROCEDURE AIRLINE_DWH.STAGE1_RAW.SP_LOAD_RAW_FROM_STAGE(RUN_ID STRING)
RETURNS STRING
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
function exec(sqlText) {
  var stmt = snowflake.createStatement({sqlText: sqlText});
  stmt.execute();
  return {rowCount: stmt.getRowCount(), queryId: stmt.getQueryId()};
}

var proc = "STAGE1_RAW.SP_LOAD_RAW_FROM_STAGE";

var copySql = `
COPY INTO AIRLINE_DWH.STAGE1_RAW.AIRLINE_RAW
  (SRC_ROW_ID, PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY,
   AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, CONTINENTS,
   DEPARTURE_DATE, ARRIVAL_AIRPORT, PILOT_NAME, FLIGHT_STATUS, TICKET_TYPE, PASSENGER_STATUS,
   SRC_FILE_NAME)
FROM (
  SELECT
    t.$1::NUMBER,
    t.$2::STRING,
    t.$3::STRING,
    t.$4::STRING,
    t.$5::STRING,
    t.$6::NUMBER,
    t.$7::STRING,
    t.$8::STRING,
    t.$9::STRING,
    t.$10::STRING,
    t.$11::STRING,
    t.$12::STRING,
    t.$13::DATE,
    t.$14::STRING,
    t.$15::STRING,
    t.$16::STRING,
    t.$17::STRING,
    t.$18::STRING,
    METADATA$FILENAME
  FROM @AIRLINE_DWH.STAGE1_RAW.AIRLINE_INT_STAGE t
)
ON_ERROR = 'ABORT_STATEMENT';
`;

var res = exec(copySql);
exec(`CALL AIRLINE_DWH.AUDIT.SP_LOG_AUDIT('${RUN_ID}', '${proc}', 'STAGE1_RAW.AIRLINE_RAW', 'INSERT', ${res.rowCount}, '${res.queryId}')`);

return "Loaded rows to STAGE1_RAW.AIRLINE_RAW: " + res.rowCount;
$$;


CREATE OR REPLACE PROCEDURE AIRLINE_DWH.STAGE2_DW.SP_TRANSFORM_RAW_TO_DW(RUN_ID STRING)
RETURNS STRING
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
function exec(sqlText) {
  var stmt = snowflake.createStatement({sqlText: sqlText});
  stmt.execute();
  return {rowCount: stmt.getRowCount(), queryId: stmt.getQueryId()};
}

function execScalar(sqlText) {
  var stmt = snowflake.createStatement({sqlText: sqlText});
  var rs = stmt.execute();
  rs.next();
  return rs.getColumnValue(1);
}

function audit(proc, target, action, res) {
  exec(`CALL AIRLINE_DWH.AUDIT.SP_LOG_AUDIT('${RUN_ID}', '${proc}', '${target}', '${action}', ${res.rowCount}, '${res.queryId}')`);
}

var proc = "STAGE2_DW.SP_TRANSFORM_RAW_TO_DW";
var src_stream = "AIRLINE_DWH.STAGE1_RAW.AIRLINE_RAW_STREAM";
var src = "SRC_BATCH";

/* Consume the stream exactly once */
exec(`CREATE OR REPLACE TEMP TABLE ${src} AS SELECT * FROM ${src_stream};`);
var batchCnt = execScalar(`SELECT COUNT(*) FROM ${src};`);

if (batchCnt == 0) {
  return "No new data in stream";
}

/* DIM_PASSENGER (type-1 update + insert) */
var updPassenger = exec(`
UPDATE AIRLINE_DWH.STAGE2_DW.DIM_PASSENGER d
SET
  FIRST_NAME = s.FIRST_NAME,
  LAST_NAME = s.LAST_NAME,
  GENDER = s.GENDER,
  AGE = s.AGE,
  NATIONALITY = s.NATIONALITY,
  PASSENGER_STATUS = s.PASSENGER_STATUS,
  UPDATED_AT = CURRENT_TIMESTAMP()
FROM (
  SELECT DISTINCT PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY, PASSENGER_STATUS
  FROM ${src}
) s
WHERE d.PASSENGER_ID = s.PASSENGER_ID
  AND (
    COALESCE(d.FIRST_NAME,'') <> COALESCE(s.FIRST_NAME,'')
    OR COALESCE(d.LAST_NAME,'') <> COALESCE(s.LAST_NAME,'')
    OR COALESCE(d.GENDER,'') <> COALESCE(s.GENDER,'')
    OR COALESCE(d.AGE,-1) <> COALESCE(s.AGE,-1)
    OR COALESCE(d.NATIONALITY,'') <> COALESCE(s.NATIONALITY,'')
    OR COALESCE(d.PASSENGER_STATUS,'') <> COALESCE(s.PASSENGER_STATUS,'')
  )
`);
audit(proc, "STAGE2_DW.DIM_PASSENGER", "UPDATE", updPassenger);

var insPassenger = exec(`
INSERT INTO AIRLINE_DWH.STAGE2_DW.DIM_PASSENGER(
  PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY, PASSENGER_STATUS
)
SELECT s.PASSENGER_ID, s.FIRST_NAME, s.LAST_NAME, s.GENDER, s.AGE, s.NATIONALITY, s.PASSENGER_STATUS
FROM (
  SELECT DISTINCT PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY, PASSENGER_STATUS
  FROM ${src}
) s
LEFT JOIN AIRLINE_DWH.STAGE2_DW.DIM_PASSENGER d
  ON d.PASSENGER_ID = s.PASSENGER_ID
WHERE d.PASSENGER_ID IS NULL
`);
audit(proc, "STAGE2_DW.DIM_PASSENGER", "INSERT", insPassenger);

/* DIM_AIRPORT */
var updAirport = exec(`
UPDATE AIRLINE_DWH.STAGE2_DW.DIM_AIRPORT d
SET
  AIRPORT_COUNTRY_CODE = s.AIRPORT_COUNTRY_CODE,
  COUNTRY_NAME = s.COUNTRY_NAME,
  AIRPORT_CONTINENT = s.AIRPORT_CONTINENT,
  CONTINENTS = s.CONTINENTS,
  UPDATED_AT = CURRENT_TIMESTAMP()
FROM (
  SELECT DISTINCT AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, CONTINENTS
  FROM ${src}
) s
WHERE d.AIRPORT_NAME = s.AIRPORT_NAME
  AND (
    COALESCE(d.AIRPORT_COUNTRY_CODE,'') <> COALESCE(s.AIRPORT_COUNTRY_CODE,'')
    OR COALESCE(d.COUNTRY_NAME,'') <> COALESCE(s.COUNTRY_NAME,'')
    OR COALESCE(d.AIRPORT_CONTINENT,'') <> COALESCE(s.AIRPORT_CONTINENT,'')
    OR COALESCE(d.CONTINENTS,'') <> COALESCE(s.CONTINENTS,'')
  )
`);
audit(proc, "STAGE2_DW.DIM_AIRPORT", "UPDATE", updAirport);

var insAirport = exec(`
INSERT INTO AIRLINE_DWH.STAGE2_DW.DIM_AIRPORT(
  AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, CONTINENTS
)
SELECT s.AIRPORT_NAME, s.AIRPORT_COUNTRY_CODE, s.COUNTRY_NAME, s.AIRPORT_CONTINENT, s.CONTINENTS
FROM (
  SELECT DISTINCT AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, CONTINENTS
  FROM ${src}
) s
LEFT JOIN AIRLINE_DWH.STAGE2_DW.DIM_AIRPORT d
  ON d.AIRPORT_NAME = s.AIRPORT_NAME
WHERE d.AIRPORT_NAME IS NULL
`);
audit(proc, "STAGE2_DW.DIM_AIRPORT", "INSERT", insAirport);

/* DIM_PILOT */
var insPilot = exec(`
INSERT INTO AIRLINE_DWH.STAGE2_DW.DIM_PILOT(PILOT_NAME)
SELECT DISTINCT s.PILOT_NAME
FROM ${src} s
LEFT JOIN AIRLINE_DWH.STAGE2_DW.DIM_PILOT d
  ON d.PILOT_NAME = s.PILOT_NAME
WHERE d.PILOT_NAME IS NULL
`);
audit(proc, "STAGE2_DW.DIM_PILOT", "INSERT", insPilot);

/* DIM_TICKET_TYPE */
var insTicket = exec(`
INSERT INTO AIRLINE_DWH.STAGE2_DW.DIM_TICKET_TYPE(TICKET_TYPE)
SELECT DISTINCT s.TICKET_TYPE
FROM ${src} s
LEFT JOIN AIRLINE_DWH.STAGE2_DW.DIM_TICKET_TYPE d
  ON d.TICKET_TYPE = s.TICKET_TYPE
WHERE d.TICKET_TYPE IS NULL
`);
audit(proc, "STAGE2_DW.DIM_TICKET_TYPE", "INSERT", insTicket);

/* DIM_STATUS */
var insStatus = exec(`
INSERT INTO AIRLINE_DWH.STAGE2_DW.DIM_STATUS(FLIGHT_STATUS, PASSENGER_STATUS)
SELECT DISTINCT s.FLIGHT_STATUS, s.PASSENGER_STATUS
FROM ${src} s
LEFT JOIN AIRLINE_DWH.STAGE2_DW.DIM_STATUS d
  ON d.FLIGHT_STATUS = s.FLIGHT_STATUS
 AND d.PASSENGER_STATUS = s.PASSENGER_STATUS
WHERE d.STATUS_SK IS NULL
`);
audit(proc, "STAGE2_DW.DIM_STATUS", "INSERT", insStatus);

/* FACT_TRIP */
var insFact = exec(`
INSERT INTO AIRLINE_DWH.STAGE2_DW.FACT_TRIP(
  PASSENGER_SK, AIRPORT_SK, ARRIVAL_AIRPORT, PILOT_SK, TICKET_TYPE_SK, STATUS_SK, DEPARTURE_DATE
)
SELECT
  dp.PASSENGER_SK,
  da.AIRPORT_SK,
  s.ARRIVAL_AIRPORT,
  dpl.PILOT_SK,
  dt.TICKET_TYPE_SK,
  ds.STATUS_SK,
  s.DEPARTURE_DATE
FROM ${src} s
JOIN AIRLINE_DWH.STAGE2_DW.DIM_PASSENGER dp ON dp.PASSENGER_ID = s.PASSENGER_ID
JOIN AIRLINE_DWH.STAGE2_DW.DIM_AIRPORT da ON da.AIRPORT_NAME = s.AIRPORT_NAME
JOIN AIRLINE_DWH.STAGE2_DW.DIM_PILOT dpl ON dpl.PILOT_NAME = s.PILOT_NAME
JOIN AIRLINE_DWH.STAGE2_DW.DIM_TICKET_TYPE dt ON dt.TICKET_TYPE = s.TICKET_TYPE
JOIN AIRLINE_DWH.STAGE2_DW.DIM_STATUS ds
  ON ds.FLIGHT_STATUS = s.FLIGHT_STATUS
 AND ds.PASSENGER_STATUS = s.PASSENGER_STATUS
`);
audit(proc, "STAGE2_DW.FACT_TRIP", "INSERT", insFact);

return "Transform complete. Batch rows=" + batchCnt + ". Fact inserted=" + insFact.rowCount;
$$;


CREATE OR REPLACE PROCEDURE AIRLINE_DWH.STAGE3_MART.SP_BUILD_MART(RUN_ID STRING)
RETURNS STRING
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
function exec(sqlText) {
  var stmt = snowflake.createStatement({sqlText: sqlText});
  stmt.execute();
  return {rowCount: stmt.getRowCount(), queryId: stmt.getQueryId()};
}
function audit(proc, target, action, res) {
  exec(`CALL AIRLINE_DWH.AUDIT.SP_LOG_AUDIT('${RUN_ID}', '${proc}', '${target}', '${action}', ${res.rowCount}, '${res.queryId}')`);
}

var proc = "STAGE3_MART.SP_BUILD_MART";

var buildFact = exec(`
CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE3_MART.FACT_TRIP_ENRICHED AS
SELECT
  f.TRIP_SK,
  p.PASSENGER_ID,
  p.FIRST_NAME || ' ' || p.LAST_NAME AS PASSENGER_NAME,
  p.GENDER,
  p.AGE,
  p.NATIONALITY,
  a.AIRPORT_NAME,
  a.AIRPORT_COUNTRY_CODE,
  a.COUNTRY_NAME,
  a.AIRPORT_CONTINENT,
  a.CONTINENTS,
  f.ARRIVAL_AIRPORT,
  pl.PILOT_NAME,
  st.FLIGHT_STATUS,
  tt.TICKET_TYPE,
  st.PASSENGER_STATUS,
  f.DEPARTURE_DATE,
  f.LOAD_TS
FROM AIRLINE_DWH.STAGE2_DW.FACT_TRIP f
JOIN AIRLINE_DWH.STAGE2_DW.DIM_PASSENGER p ON p.PASSENGER_SK = f.PASSENGER_SK
JOIN AIRLINE_DWH.STAGE2_DW.DIM_AIRPORT a ON a.AIRPORT_SK = f.AIRPORT_SK
JOIN AIRLINE_DWH.STAGE2_DW.DIM_PILOT pl ON pl.PILOT_SK = f.PILOT_SK
JOIN AIRLINE_DWH.STAGE2_DW.DIM_TICKET_TYPE tt ON tt.TICKET_TYPE_SK = f.TICKET_TYPE_SK
JOIN AIRLINE_DWH.STAGE2_DW.DIM_STATUS st ON st.STATUS_SK = f.STATUS_SK
`);
audit(proc, "STAGE3_MART.FACT_TRIP_ENRICHED", "CREATE_OR_REPLACE", buildFact);

var buildKpi = exec(`
CREATE OR REPLACE TABLE AIRLINE_DWH.STAGE3_MART.DAILY_KPI AS
SELECT
  DEPARTURE_DATE AS KPI_DATE,
  CONTINENTS,
  COUNT(*) AS FLIGHTS_CNT,
  COUNT(DISTINCT PASSENGER_ID) AS UNIQUE_PASSENGERS,
  CURRENT_TIMESTAMP() AS UPDATED_AT
FROM AIRLINE_DWH.STAGE3_MART.FACT_TRIP_ENRICHED
GROUP BY 1,2
`);
audit(proc, "STAGE3_MART.DAILY_KPI", "CREATE_OR_REPLACE", buildKpi);

return "Mart built";
$$;
