-- 03_security.sql

CREATE OR REPLACE ROW ACCESS POLICY AIRLINE_DWH.SECURITY.RAP_CONTINENTS
AS (CONTINENTS STRING) RETURNS BOOLEAN ->
  CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN TRUE
    WHEN CURRENT_ROLE() IN ('ANALYST_NAM') THEN CONTINENTS = 'North America'
    WHEN CURRENT_ROLE() IN ('ANALYST_EU')  THEN CONTINENTS = 'Europe'
    ELSE FALSE
  END;

ALTER TABLE AIRLINE_DWH.STAGE3_MART.FACT_TRIP_ENRICHED
  ADD ROW ACCESS POLICY AIRLINE_DWH.SECURITY.RAP_CONTINENTS ON (CONTINENTS);

CREATE OR REPLACE SECURE VIEW AIRLINE_DWH.SECURITY.VW_FACT_TRIP_SECURE AS
SELECT * FROM AIRLINE_DWH.STAGE3_MART.FACT_TRIP_ENRICHED;
