-- 04_time_travel_examples.sql

USE DATABASE AIRLINE_DWH;

-- DDL #1: DROP + UNDROP
DROP TABLE IF EXISTS STAGE3_MART.DAILY_KPI;
UNDROP TABLE STAGE3_MART.DAILY_KPI;

-- DDL #2: CLONE at a point in time (пример: 5 минут назад)
CREATE OR REPLACE TABLE STAGE3_MART.FACT_TRIP_ENRICHED_CLONE
  CLONE STAGE3_MART.FACT_TRIP_ENRICHED
  AT (OFFSET => -60*5);

-- DML #1: UPDATE + BEFORE
UPDATE STAGE2_DW.DIM_PASSENGER
SET NATIONALITY = 'TEST_NATIONALITY'
WHERE PASSENGER_ID IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (ORDER BY PASSENGER_ID) = 1;

SELECT *
FROM STAGE2_DW.DIM_PASSENGER
  BEFORE (STATEMENT => LAST_QUERY_ID());

-- DML #2: DELETE + AT
DELETE FROM STAGE1_RAW.AIRLINE_RAW
WHERE SRC_ROW_ID IN (0,1);

SELECT COUNT(*)
FROM STAGE1_RAW.AIRLINE_RAW
  AT (OFFSET => -60*2);
